version: "3.8"
services:
  bot:
    build: .
    container_name: sumire_vox_bot
    volumes:
      - .:/app
    depends_on:
      - db
      - voicevox_engine
    links:
      - db
      - voicevox_engine
    env_file:
      - .env
    networks:
      - sumire_vox_network
    ports:
      - "8080:8080"
  voicevox_engine:
    image: voicevox/voicevox_engine:cpu-ubuntu20.04-latest
    container_name: voicevox_engine
    ports:
      - "50021:50021"
    restart: unless-stopped
    volumes:
      - ./voicevox_config:/root/.local/share/voicevox_engine
    networks:
      - sumire_vox_network
  db:
    image: postgres:15
    container_name: sumire_vox_db
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: sumire_vox
    ports:
      - "5432:5432"
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    networks:
      - sumire_vox_network
networks:
  sumire_vox_network:
    driver: bridge
