version: "3.8"
name: sumirevox

# 共通設定の定義
x-bot-template: &bot-template
  build:
    context: .
  volumes:
    - .:/app
  depends_on:
    db:
      condition: service_healthy
    voicevox_engine:
      condition: service_started
  restart: unless-stopped

services:
  bot1:
    <<: *bot-template
    container_name: sumirevox_bot_1
    env_file:
      - ./.env
      - ./.env.bot1
    networks:
      - sumirevox_network

  bot2:
    <<: *bot-template
    container_name: sumirevox_bot_2
    env_file:
      - ./.env
      - ./.env.bot2
    networks:
      - sumirevox_network

  bot3:
    <<: *bot-template
    container_name: sumirevox_bot_3
    env_file:
      - ./.env
      - ./.env.bot3
    networks:
      - sumirevox_network

  voicevox_engine:
    image: voicevox/voicevox_engine:nvidia-ubuntu20.04-latest
    container_name: voicevox_engine
    ports:
      - "50021:50021"
    tty: true
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities:
                - gpu
    restart: unless-stopped
    volumes:
      - ./voicevox_config:/root/.local/share/voicevox_engine
    networks:
      - sumirevox_network

  db:
    image: postgres:15
    container_name: sumirevox_db
    restart: always
    env_file:
      - ./.env
    ports:
      - "5432:5432"
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB" ]
      interval: 5s
      timeout: 5s
      retries: 30
    networks:
      - sumirevox_network

networks:
  sumirevox_network:
    driver: bridge